"""Compatibility façade for validation helpers and CLI."""

from __future__ import annotations

from scripts.validation.events import (
    DEFAULT_ALLOWED_RECORD_TYPES,
    FILENAME_DATE_PATTERN,
    ISO_YEAR_PATTERN,
    YEAR_PATTERN,
    _check_event_type,
    _get_started_year,
    validate_event_ledgers,
)
from scripts.validation.instrument import (
    INSTRUMENT_ID_PATTERN,
    _append_light_path_route_warnings,
    _append_name_model_redundancy_warnings,
    _append_product_code_redundancy_warnings,
    _build_canonical_instrument_payload,
    _check_rule_validation,
    _check_type,
    _coerce_number,
    _is_descriptive_wavelength,
    _is_numeric_string,
    _is_positive_number,
    _is_positive_number_or_numeric_string,
    _is_valid_instrument_id,
    _is_valid_wavelength,
    _legacy_instrument_topology_paths,
    build_instrument_completeness_report,
    validate_instrument_ledgers,
)
from scripts.validation.io import _is_non_empty_string, _is_number
from scripts.validation.model import (
    EventPolicy,
    EventValidationReport,
    InstrumentCompletenessReport,
    InstrumentPolicy,
    PolicyRule,
    ResolvedNode,
    ValidationIssue,
    VocabularyTerm,
)
from scripts.validation.policy import (
    _build_item_field_vocab_index,
    _context_item_alias_present,
    _evaluate_event_required_if,
    _evaluate_required_if,
    _get_software_roles,
    _list_context_path,
    _load_event_policy,
    _load_instrument_policy,
    _nodes_have_present_value,
    _parent_path_from_list_path,
    _resolve_path_nodes,
    _resolve_rule_nodes,
    load_policy,
)
from scripts.validation.reporting import main, print_validation_report
from scripts.validation.vocabulary import Vocabulary

__all__ = [
    "DEFAULT_ALLOWED_RECORD_TYPES",
    "FILENAME_DATE_PATTERN",
    "ISO_YEAR_PATTERN",
    "YEAR_PATTERN",
    "_check_event_type",
    "_get_started_year",
    "validate_event_ledgers",
    "INSTRUMENT_ID_PATTERN",
    "_append_light_path_route_warnings",
    "_append_name_model_redundancy_warnings",
    "_append_product_code_redundancy_warnings",
    "_build_canonical_instrument_payload",
    "_check_rule_validation",
    "_check_type",
    "_coerce_number",
    "_get_software_roles",
    "_is_descriptive_wavelength",
    "_is_non_empty_string",
    "_is_number",
    "_is_numeric_string",
    "_is_positive_number",
    "_is_positive_number_or_numeric_string",
    "_is_valid_instrument_id",
    "_is_valid_wavelength",
    "_legacy_instrument_topology_paths",
    "build_instrument_completeness_report",
    "validate_instrument_ledgers",
    "EventPolicy",
    "EventValidationReport",
    "InstrumentCompletenessReport",
    "InstrumentPolicy",
    "PolicyRule",
    "ResolvedNode",
    "ValidationIssue",
    "VocabularyTerm",
    "_build_item_field_vocab_index",
    "_context_item_alias_present",
    "_evaluate_event_required_if",
    "_evaluate_required_if",
    "_list_context_path",
    "_load_event_policy",
    "_load_instrument_policy",
    "_nodes_have_present_value",
    "_parent_path_from_list_path",
    "_resolve_path_nodes",
    "_resolve_rule_nodes",
    "load_policy",
    "main",
    "print_validation_report",
    "Vocabulary",
]


if __name__ == "__main__":
    raise SystemExit(main())
